version: '3'
services:
  app:
    build:
      context: .
      dockerfile: cuda.dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    volumes:
      - "D:/records:/data/records"

